# oidc.yml - a docker-compose override that adds a oidc IDP to the stack
#
# Once running, head to `localhost:8000/simplesaml/` to get access to the IDP
#
# There are 2 users and an admin account:
# user1:user1pass
# user2:user2pass
# admin:secret
#
# ref: https://hub.docker.com/r/kristophjunge/test-saml-idp/
# ref: https://docs.docker.com/compose/extends/
#
version: '3'

services:
  web:
    environment:
      # CONCOURSE_MAIN_TEAM_OIDC_USER: qux
      CONCOURSE_MAIN_TEAM_OIDC_GROUP: group1

      CONCOURSE_OIDC_ISSUER: http://oidc:9000
      CONCOURSE_OIDC_CLIENT_ID: foo
      CONCOURSE_OIDC_CLIENT_SECRET: bar
      CONCOURSE_OIDC_SKIP_SSL_VALIDATION: "true"
      CONCOURSE_OIDC_USER_NAME_KEY: name

  oidc:
    image: qlik/simple-oidc-provider
    ports:
    - 9000:9000
    environment:
      REDIRECTS: http://localhost:8080/sky/issuer/callback
      CONFIG_FILE: /oidc/config.json
      USERS_FILE: /oidc/users.json
    volumes:
    - ./hack/oidc:/oidc

